// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzlXgoT87iu-xv1bZVH0TEVNe0tEo0gA',
    appId: '1:79324128247:web:c7df637be7c762a83344f2',
    messagingSenderId: '79324128247',
    projectId: 'hume-dc192',
    authDomain: 'hume-dc192.firebaseapp.com',
    storageBucket: 'hume-dc192.appspot.com',
    measurementId: 'G-WMTQ9KH4DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT5rVrNEMp1xsL1h35hf9715PA81D0P8s',
    appId: '1:79324128247:android:294e53dd61990b443344f2',
    messagingSenderId: '79324128247',
    projectId: 'hume-dc192',
    storageBucket: 'hume-dc192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl99s0GtKxCAqOrXzG_62DZhXgEP6HSWo',
    appId: '1:79324128247:ios:d051de321fd5e61a3344f2',
    messagingSenderId: '79324128247',
    projectId: 'hume-dc192',
    storageBucket: 'hume-dc192.appspot.com',
    iosBundleId: 'com.tritec.humeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl99s0GtKxCAqOrXzG_62DZhXgEP6HSWo',
    appId: '1:79324128247:ios:f08b257c39c831cd3344f2',
    messagingSenderId: '79324128247',
    projectId: 'hume-dc192',
    storageBucket: 'hume-dc192.appspot.com',
    iosBundleId: 'com.tritec.humeAdmin.RunnerTests',
  );
}
